sonar.projectKey=se_red
sonar.qualitygate.wait=true
#Specify Python version to get better results
sonar.python.version=3
#Exclude XML files from Sonar analysis
sonar.exclusions=**/*.xml, infra/**, pizza_1337_preact/**/*.*