sonar.projectKey=se_red
sonar.qualitygate.wait=true
#Specify Python version to get better results
sonar.python.version=3
# Specify the coverage file
sonar.python.coverage.reportPaths=integration_coverage.xml
#Exclude XML files from Sonar analysis
sonar.exclusions=**/*.xml, **/infra/**, **/pizza_1337_preact/**/*.*, **/tests/**/*.*, **/router.py, **/nominatim_error.py, **/doc/**/*.*,
                    **/env.py, **/main.py