sonar.projectKey=se_red
sonar.qualitygate.wait=true

#Specify Python version to get better results
sonar.python.version=3
#Exclude XML files from Sonar analysis
sonar.exclusions=/.xml, infra/, pizza_1337_preact//.*
# Specify the coverage file
sonar.python.coverage.reportPaths=integration_coverage.xml
sonar.coverage.exclusions=/database//., */exclude.py, **/tests//.*, **/router.py, **/main.py, **/schemas.py, **/nominatim_error.py