"""Pizza_Service_DB

Revision ID: 13d9d2963cc7
Revises: 40ae859bce90
Create Date: 2025-10-24 10:49:28.351372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d9d2963cc7'
down_revision = '40ae859bce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
