"""New Sauce column for pizza_type

Revision ID: aa1c55d08052
Revises: f3f980614bb7
Create Date: 2026-01-13 17:05:42.049047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1c55d08052'
down_revision = 'f3f980614bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
