"""updated OrderStatuses in models

Revision ID: d08ecf326c60
Revises: bcf0bd3efb4a
Create Date: 2025-12-02 13:55:54.623746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08ecf326c60'
down_revision = 'bcf0bd3efb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
