"""my_new_feature

Revision ID: e864de6a6e0e
Revises: fc8f161785f3
Create Date: 2026-01-13 18:19:40.620840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e864de6a6e0e'
down_revision = 'fc8f161785f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
