"""add missing sauce_id column

Revision ID: fc8f161785f3
Revises: 385c697a9215
Create Date: 2026-01-11 17:45:26.061236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8f161785f3'
down_revision = '385c697a9215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza_type', sa.Column('sauce_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'pizza_type', 'sauce', ['sauce_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pizza_type', type_='foreignkey')
    op.drop_column('pizza_type', 'sauce_id')
    # ### end Alembic commands ###
