export const ACTION_FETCH_ALL_AWAIT = "ACTION_FETCH_ALL_AWAIT";

export const ACTION_CREATE_PREMADE_DOUGH = "ACTION_CREATE_PREMADE_DOUGH"
export const ACTION_CREATE_DOUGH = "ACTION_CREATE_DOUGH"
export const ACTION_UPDATE_DOUGH_STOCK = "ACTION_UPDATE_DOUGH_STOCK"
export const ACTION_DELETE_DOUGHS = "ACTION_DELETE_DOUGHS"
export const ACTION_FETCH_DOUGHS = "ACTION_FETCH_DOUGHS"
export const DISPATCH_START_FETCH_DOUGHS = 'DISPATCH_START_FETCH_DOUGHS'
export const DISPATCH_FETCH_DOUGHS_RESULT = 'DISPATCH_FETCH_DOUGHS_RESULT'
export const DISPATCH_FETCH_DOUGHS_ERROR = 'DISPATCH_FETCH_DOUGHS_ERROR'


export const ACTION_CREATE_TOPPING = "ACTION_CREATE_TOPPING"
export const ACTION_CREATE_PREMADE_TOPPING = "ACTION_CREATE_PREMADE_TOPPING"
export const ACTION_DELETE_TOPPINGS = "ACTION_DELETE_TOPPINGS"
export const ACTION_FETCH_TOPPINGS = "ACTION_FETCH_TOPPINGS"
export const ACTION_UPDATE_TOPPING_STOCK = "ACTION_UPDATE_TOPPING_STOCK"

export const DISPATCH_START_FETCH_TOPPINGS = 'DISPATCH_START_FETCH_TOPPINGS'
export const DISPATCH_FETCH_TOPPINGS_RESULT = 'DISPATCH_FETCH_TOPPINGS_RESULT'
export const DISPATCH_FETCH_TOPPINGS_ERROR = 'DISPATCH_FETCH_TOPPINGS_ERROR'

 
export const ACTION_CREATE_BEVERAGE = "ACTION_CREATE_BEVERAGE"
export const ACTION_CREATE_PREMADE_BEVERAGE = "ACTION_CREATE_PREMADE_BEVERAGE"
export const ACTION_FETCH_BEVERAGES = "ACTION_FETCH_BEVERAGES"
export const DISPATCH_START_FETCH_BEVERAGES = 'DISPATCH_START_FETCH_BEVERAGES'
export const DISPATCH_FETCH_BEVERAGES_RESULT = 'DISPATCH_FETCH_BEVERAGES_RESULT'
export const DISPATCH_FETCH_BEVERAGES_ERROR = 'DISPATCH_FETCH_BEVERAGES_ERROR'
export const ACTION_UPDATE_BEVERAGE_STOCK = "ACTION_UPDATE_BEVERAGE_STOCK"
export const ACTION_DELETE_BEVERAGES = "ACTION_DELETE_BEVERAGES"

export const ACTION_FETCH_ORDERS = "ACTION_FETCH_ORDERS"
export const ACTION_CREATE_ORDER = "ACTION_CREATE_ORDER"
export const ACTION_DELETE_ORDERS = "ACTION_DELETE_ORDERS"
export const ACTION_DELETE_ORDERS_AND_FETCH = "ACTION_DELETE_ORDERS_AND_FETCH"
export const DISPATCH_START_FETCH_ORDERS  = 'DISPATCH_START_FETCH_ORDERS'
export const DISPATCH_FETCH_ORDERS_RESULT = 'DISPATCH_FETCH_ORDERS_RESULT'
export const DISPATCH_FETCH_ORDERS_ERROR  = 'DISPATCH_FETCH_ORDERS_ERROR'

export const ACTION_FETCH_ORDER_CREATE_DATA = 'ACTION_FETCH_ORDER_CREATE_DATA'

export const ACTION_FETCH_ORDER_DETAILS = "ACTION_FETCH_ORDER_DETAILS"
export const DISPATCH_START_FETCH_ORDER_DETAILS  = 'DISPATCH_START_FETCH_ORDER_DETAILS';
export const DISPATCH_FETCH_ORDER_DETAILS_PIZZA_TYPES_RESULT = 'DISPATCH_FETCH_ORDER_DETAILS_PIZZA_TYPES_RESULT';
export const DISPATCH_FETCH_ORDER_DETAILS_PRICE_RESULT = 'DISPATCH_FETCH_ORDER_DETAILS_PRICE_RESULT';
export const DISPATCH_FETCH_ORDER_DETAILS_BEVERAGES_RESULT = 'DISPATCH_FETCH_ORDER_DETAILS_BEVERAGES_RESULT';
export const DISPATCH_END_FETCH_ORDER_DETAILS = 'DISPATCH_END_FETCH_ORDER_DETAILS'
export const DISPATCH_FETCH_ORDER_DETAILS_ERROR  = 'DISPATCH_FETCH_ORDER_DETAILS_ERROR';


export const ACTION_FETCH_PIZZA_TYPES = "ACTION_FETCH_PIZZA_TYPES"
export const DISPATCH_START_FETCH_PIZZA_TYPES = 'DISPATCH_START_FETCH_PIZZA_TYPES'
export const DISPATCH_FETCH_PIZZA_TYPES_RESULT = 'DISPATCH_FETCH_PIZZA_TYPES_RESULT'
export const DISPATCH_FETCH_PIZZA_TYPES_ERROR = 'DISPATCH_FETCH_PIZZA_TYPES_ERROR'
export const ACTION_CREATE_PIZZA_TYPE = "ACTION_CREATE_PIZZA_TYPE"

export const ACTION_FETCH_PIZZA_TYPE_CREATE_DATA = "ACTION_FETCH_PIZZA_TYPE_CREATE_DATA"

export const ACTION_DELETE_PIZZA_TYPES = "ACTION_DELETE_PIZZA_TYPES"
export const ACTION_DELETE_PIZZA_TYPES_AND_FETCH = "ACTION_DELETE_PIZZA_TYPES_AND_FETCH"


export const ACTION_FETCH_USERS = "ACTION_FETCH_USERS";
export const DISPATCH_START_FETCH_USERS = 'DISPATCH_START_FETCH_USERS'
export const DISPATCH_FETCH_USERS_RESULT = 'DISPATCH_FETCH_USERS_RESULT'
export const DISPATCH_FETCH_USERS_ERROR = 'DISPATCH_FETCH_USERSS_ERROR'
export const ACTION_CHECK_DEFAULT_USER = "ACTION_CHECK_DEFAULT_USER";

export const ACTION_DELETE_ALL = "ACTION_DELETE_ALL"

export const ACTION_SERVER_ERROR = "ACTION_SERVER_ERROR"
export const ACTION_SERVER_ERROR_HANDLED = "ACTION_SERVER_ERROR_HANDLED"

export const DISPATCH_ADD_SERVER_ERROR = "DISPATCH_ADD_SERVER_ERROR";
export const DISPATCH_REMOVE_SERVER_ERROR = "DISPATCH_REMOVE_SERVER_ERROR";

export const ACTION_SET_SERVER_ACTION_IN_PROGRESS = "ACTION_SET_SERVER_ACTION_IN_PROGRESS"
export const DISPATCH_SET_SERVER_ACTION_IN_PROGRESS = "DISPATCH_SET_SERVER_ACTION_IN_PROGRESS"
